site_name: Showcase
nav:
  - Home: index.md
  - Roadmap: roadmap.md
  - Architecture: architecture.md
plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
theme:
  name: material
